default_platform(:ios)

TEAMID = ENV["TEAMID"]
GH_PAT = ENV["GH_PAT"]
GITHUB_WORKSPACE = ENV["GITHUB_WORKSPACE"]
GITHUB_REPOSITORY_OWNER = ENV["GITHUB_REPOSITORY_OWNER"]
FASTLANE_KEY_ID = ENV["FASTLANE_KEY_ID"]
FASTLANE_ISSUER_ID = ENV["FASTLANE_ISSUER_ID"]
FASTLANE_KEY = ENV["FASTLANE_KEY"]
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

# IDENTIFIANT UNIQUE (Ce que tu as créé chez Apple)
MY_BUNDLE_ID = "com.aurelien.xdrip4ios"

platform :ios do
  desc "Build Xdrip4iOS"
  lane :build_xdrip4ios do
    setup_ci if ENV['CI']
    
    update_project_team(
      path: "#{GITHUB_WORKSPACE}/xdrip.xcodeproj",
      teamid: "#{TEAMID}"
    )

    api_key = app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )

    # On récupère le numéro de build chez Apple
    previous_build_number = latest_testflight_build_number(
      app_identifier: MY_BUNDLE_ID,
      api_key: api_key,
    )

    current_build_number = previous_build_number + 1

    increment_build_number(
      xcodeproj: "#{GITHUB_WORKSPACE}/xdrip.xcodeproj",
      build_number: current_build_number
    )
    
    # Signature des certificats
    match(
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64("#{GITHUB_REPOSITORY_OWNER}:#{GH_PAT}"),
      app_identifier: [MY_BUNDLE_ID]
    )

    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]

    # Application des réglages de signature au projet Xcode
    update_code_signing_settings(
      path: "#{GITHUB_WORKSPACE}/xdrip.xcodeproj",
      profile_name: mapping[MY_BUNDLE_ID],
      code_sign_identity: "iPhone Distribution",
      targets: ["xdrip"]
    )
    
    # Compilation
    gym(
      export_method: "app-store",
      scheme: "xdrip",
      output_name: "Xdrip4iOS.ipa",
      configuration: "Release",
      destination: 'generic/platform=iOS',
      buildlog_path: 'buildlog'
    )

    copy_artifacts(
      target_path: "artifacts",
      artifacts: ["*.mobileprovision", "*.ipa", "*.dSYM.zip"]
    )
  end

  desc "Push to TestFlight"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "#{FASTLANE_KEY_ID}",
      issuer_id: "#{FASTLANE_ISSUER_ID}",
      key_content: "#{FASTLANE_KEY}"
    )
    
    upload_to_testflight(
      api_key: api_key,
      skip_submission: false,
      ipa: "Xdrip4iOS.ipa",
      skip_waiting_for_build_processing: true,
    )
  end
end
